### ISSUE TITLE
Fit the navigations options size

### ISSUE THREAD

**Issue by pedrormiguel** [pedrormiguel/TomatoTimerClone#1]
The last option 'Tweet about us' has more space than need it, it has to be centered and just with a bit of padding around it.

<img width="1440" alt="Screen Shot 2021-03-17 at 6 26 41 PM" src="https://user-images.githubusercontent.com/62821333/111546640-5cdb3200-874e-11eb-85bf-beb844664e7f.png">

**Comment by ashwindevx** [comment]
Can i work on this issue?

**Comment by pedrormiguel** [comment]
Of course, Go Ahead.

**Comment by ashwindevx** [comment]
@pedrormiguel I can't find the HTML and CSS for this issue. Can you tell me?

**Comment by pedrormiguel** [comment]
The HTML file for this 'view' is _Layout.cshtml, the specific section is inside the tag 'header'  

![Screen Shot 2021-03-20 at 2 03 02 PM](https://user-images.githubusercontent.com/62821333/111881022-fee45f80-8984-11eb-9cc3-0ebcaf6c8ba9.png)

The global resource is under  wwwroot folder, 

![Screen Shot 2021-03-20 at 2 02 28 PM](https://user-images.githubusercontent.com/62821333/111881003-e96f3580-8984-11eb-900c-ef9040dc8620.png)

@ashwindevx , Let me know if there's anything else that I can do to help you. 

The original design is from https://tomato-timer.com/

**Comment by pedrormiguel** [comment]
Fixed and the lasted push to master.
